export const projects = [
  {
    id: "skystream",
    featured: true,
    tag: "Featured Project",
    tagColor: "accent",
    title: "SkyStream",
    desc: "Real-time global flight tracking pipeline. Ingests ADS-B telemetry from ~9,000 aircraft every 10 seconds via Kafka to Spark Structured Streaming to Redis, rendered on a GPU-accelerated deck.gl map with sub-5-second end-to-end latency. Includes email landing alerts and 48-hour historical trail queries via TimescaleDB. Demonstrates real-time system visibility and low-latency operational monitoring at scale.",
    stack: ["Python", "Apache Kafka", "Spark Streaming", "Redis", "TimescaleDB", "FastAPI", "deck.gl", "Docker"],
    links: [
      { label: "Live Demo", href: "http://173.212.237.120:5173", primary: true },
      { label: "GitHub", href: "https://github.com/stanik0n/skystream" },
      { label: "Blog Post", href: "/blog/skystream" },
    ],
  },
{
    id: "finsight",
    featured: false,
    tag: "Full-Stack Product",
    tagColor: "accent2",
    title: "FinSight",
    desc: "AI-assisted financial analytics platform that brings market dashboards, portfolio intelligence, research notes, curated news, and Telegram delivery into one full-stack product powered by FastAPI, React, DuckDB, Spark, Kafka, and dbt. Enables near real-time financial analysis and decision-making workflows by combining streaming data pipelines with scalable analytics and intuitive querying.",
    stack: ["React", "FastAPI", "DuckDB", "Apache Spark", "Apache Kafka", "dbt", "Telegram", "Docker"],
    links: [
      { label: "Live Demo", href: "https://finsight.rajeshchowdary.com/", primary: true },
      { label: "GitHub", href: "https://github.com/stanik0n/finsight" },
      { label: "Blog Post", href: "/blog/finsight" },
    ],
  },
  {
    id: "demand-forecasting",
    featured: false,
    tag: "ML · Supply Chain",
    tagColor: "accent2",
    title: "M5 Demand Forecasting & Inventory Replenishment",
    desc: "End-to-end ML pipeline built on Walmart's M5 dataset. Compares LightGBM gradient boosting against moving-average and seasonal-naive baselines, simulates reorder points with configurable safety-stock calculations, and delivers results through a three-persona Streamlit dashboard covering executive KPIs, model comparison, and planner-level replenishment recommendations.",
    stack: ["Python", "LightGBM", "Streamlit", "Pandas", "Parquet"],
    links: [
      { label: "Live Demo", href: "https://forecasting-9axkqjqv2oaebabshqbxjj.streamlit.app/", primary: true },
      { label: "GitHub", href: "https://github.com/stanik0n/demandforecasting" },
      { label: "Blog Post", href: "/blog/demand-forecasting" },
    ],
  },
  {
    id: "url-shortener",
    featured: false,
    tag: "System Design",
    tagColor: "accent2",
    title: "Scalable URL Shortener",
    desc: "Cache-first URL shortener engineered for high read throughput. Redis handles the redirect hot path; async background workers flush click counters to PostgreSQL in batches. Real-time analytics UI supports operational monitoring and decision-making workflows. One-command Docker Compose deploy.",
    stack: ["FastAPI", "Redis", "PostgreSQL", "Docker", "Python"],
    links: [
      { label: "GitHub", href: "https://github.com/stanik0n/url-shortener", primary: true },
      { label: "Blog Post", href: "/blog/url-shortener" },
    ],
  },
  {
    id: "nypd",
    featured: false,
    tag: "Data Analytics",
    tagColor: "accent",
    title: "NYPD Arrests Pipeline",
    desc: "End-to-end analytics pipeline over 500K+ NYPD arrest records (2023-2024). Cleaned with Alteryx, modeled dimensionally, loaded to BigQuery for sub-second aggregations, visualized in an interactive Power BI dashboard by borough, offense type, and demographics. Transforms raw public data into structured datasets and dashboards for analyzing trends across geography and time.",
    stack: ["Alteryx", "BigQuery", "SQL", "Power BI", "Python"],
    links: [{ label: "Blog Post", href: "/blog/nypd-arrests", primary: true }],
  },
  {
    id: "ev-adoption",
    featured: false,
    tag: "Data Visualization",
    tagColor: "accent2",
    title: "EV Adoption Analysis",
    desc: "Visual deep-dive into U.S. electric vehicle adoption from 2010-2024. Analyzes charging infrastructure gaps, state-by-state adoption rates, and federal policy impact from 200K EVs in 2013 to over 4 million by 2024.",
    stack: ["Python", "Data Viz", "Public Data"],
    links: [{ label: "Blog Post", href: "/blog/ev-adoption", primary: true }],
  },
  {
    id: "cnc",
    featured: false,
    tag: "Hardware + IoT",
    tagColor: "accent3",
    title: "DIY CNC Plotter",
    desc: "2-axis CNC plotting machine built with Arduino UNO + GRBL firmware, 3D-printed components, and NEMA 17 stepper motors. Extended with an ESP32 IoT layer for wireless G-code transmission, browser-based control, and real-time telemetry.",
    stack: ["Arduino", "ESP32", "Python", "GRBL", "IoT"],
    links: [{ label: "Blog Post", href: "/blog/cnc-plotter", primary: true }],
  },
];

export const posts = [
  {
    id: "skystream",
    tag: "Case Study · Deep Dive",
    title: "Building SkyStream: A Real-Time Flight Tracking Pipeline",
    desc: "Every layer of the system: Kafka checkpoint gotchas that blanked the map, why Redis writes must precede Postgres, how deck.gl handles 9,000+ GPU-accelerated points, and the four production bugs I actually hit.",
    date: "2026",
    meta: "Kafka · Spark · Redis · deck.gl · TimescaleDB",
    href: "/blog/skystream",
    featured: true,
  },
  {
    id: "finsight",
    tag: "Full-Stack Product",
    title: "Building FinSight: An AI-Assisted Financial Analytics Platform",
    desc: "How I combined market data pipelines, warehouse modeling, portfolio tooling, news aggregation, and a natural-language query layer into one end-to-end investing product.",
    date: "Apr 6, 2026",
    meta: "React, FastAPI, DuckDB, Spark, Kafka, dbt",
    href: "/blog/finsight",
    featured: false,
  },
  {
    id: "demand-forecasting",
    tag: "ML · Supply Chain",
    title: "Building an M5 Demand Forecasting & Inventory Replenishment Pipeline",
    desc: "How LightGBM, leakage-safe feature engineering, and a safety-stock simulation combine to turn Walmart's M5 dataset into actionable replenishment recommendations, with a three-persona Streamlit dashboard at the end.",
    date: "Apr 15, 2026",
    meta: "Python · LightGBM · Streamlit · Parquet",
    href: "/blog/demand-forecasting",
    featured: false,
  },
  {
    id: "url-shortener",
    tag: "System Design",
    title: "Building a Scalable URL Shortener from Scratch",
    desc: "How cache-first architecture and async click tracking combine to build a URL shortener that stays fast under heavy read load without sacrificing analytics accuracy.",
    date: "Feb 10, 2026",
    meta: "FastAPI · Redis · PostgreSQL",
    href: "/blog/url-shortener",
    featured: false,
  },
  {
    id: "nypd-arrests",
    tag: "Data Analytics",
    title: "NYPD Arrests Analysis Using Alteryx, BigQuery, and Power BI",
    desc: "Profiling, cleaning, and modeling 500K+ arrest records into an interactive Power BI dashboard that surfaces borough-level crime patterns and demographic trends.",
    date: "Nov 11, 2025",
    meta: "Alteryx · BigQuery · Power BI",
    href: "/blog/nypd-arrests",
    featured: false,
  },
  {
    id: "ev-adoption",
    tag: "Data Visualization",
    title: "EV Adoption Across the U.S. - A Visual Blog",
    desc: "From 200K EVs in 2013 to over 4 million by 2024, a state-by-state breakdown of adoption rates, charging infrastructure gaps, and the policy drivers behind the transition.",
    date: "Oct 29, 2025",
    meta: "Python · Data Viz",
    href: "/blog/ev-adoption",
    featured: false,
  },
];

export const experience = [
  {
    date: "2025 – Present",
    company: "WoMen of Connections Ministry",
    role: "Analytics Engineer (Data Analyst - Engineering)",
    points: [
      "Built and scaled a centralized analytics layer integrating multiple operational data sources, enabling real-time visibility into inventory movement, demand patterns, and resource distribution across operations.",
      "Unified 6 data sources into a single analytics layer, eliminating 20+ hours per week of manual reconciliation and improving overall data consistency and reliability.",
      "Implemented validation, deduplication, and reconciliation logic across inventory and distribution datasets, reducing discrepancies by 40% and strengthening operational reporting accuracy.",
      "Developed KPI frameworks tracking inventory flows, resource utilization, and demand variability, standardizing reporting across supply chain workflows.",
      "Enabled stakeholders to identify inefficiencies in allocation, improving planning, replenishment decisions, and overall operational efficiency.",
    ],
  },
  {
    date: "2024 – 2025",
    company: "University of Houston",
    role: "Instructional Assistant (Data & Analytics)",
    points: [
      "Assisted 140+ students across SQL and analytics coursework, improving understanding of data analysis and reporting concepts.",
      "Built performance dashboards to help faculty identify at-risk students and improve course planning and outcomes.",
      "Supported data-driven decision-making by helping faculty apply analytics to course performance and student engagement.",
    ],
  },
  {
    date: "2020 – 2023",
    company: "Brainovision Solutions (Consulting)",
    role: "Data Engineer",
    points: [
      "Delivered data engineering and analytics solutions across supply chain and retail domains, supporting demand planning, inventory tracking, and operational decision-making.",
      "Built data pipelines enabling near real-time visibility into inventory movement and warehouse operations, improving responsiveness across distribution systems.",
      "Designed dimensional data models for inventory, supplier performance, and shipment analytics, improving reporting consistency and planning accuracy.",
      "Analyzed supplier performance, lead times, and demand trends to support procurement planning and supply-demand alignment.",
      "Reduced data latency from 12+ hours to under 1 hour using optimized batch and streaming pipelines.",
      "Improved query performance and reduced compute costs through efficient data modeling and transformation strategies.",
    ],
  },
];

export const skills = [
  { group: "Languages & Query", tags: ["Python", "SQL", "Java", "SparkSQL"] },
  { group: "Data Engineering", tags: ["Apache Kafka", "Apache Spark", "Apache Airflow", "Hadoop", "dbt"] },
  { group: "Cloud Platforms", tags: ["AWS", "Azure", "GCP", "Snowflake", "Databricks"] },
  { group: "Databases & Storage", tags: ["PostgreSQL", "MySQL", "MongoDB", "DynamoDB", "BigQuery", "Redshift", "TimescaleDB"] },
  { group: "ML & Analytics", tags: ["Scikit-learn", "NumPy", "Pandas"] },
  { group: "Visualization & Tools", tags: ["Power BI", "Tableau", "QuickSight", "Docker", "Git"] },
];
